
###
GET http://localHost:3000/api/pedido_resolucion/


### Post pedido
POST http://localHost:3000/api/pedido_resolucion/
Content-Type: application/json

{
  "direccion_pedido_resolucion": "texto direccion 9999",
  "descripcion_pedido_resolucion": "texto descripcion",
  "zona": "68d2e063a55f7d39d31ae66f",
  "denunciante": "68d2e178a55f7d39d31ae674"
}

###
POST http://localHost:3000/api/anomalia/
Content-Type: application/json

{
  "pedido_resolucion": "68d2e6a0c6aaf849b83c4eea",
  "tipo_anomalia": "68d2e0a8a55f7d39d31ae673"
}

###
POST http://localHost:3000/api/anomalia/
Content-Type: application/json

{
  "pedido_resolucion": "68d2e6a0c6aaf849b83c4eea",
  "tipo_anomalia": "68d2e0a8a55f7d39d31ae673"
}


###
DELETE  http://localHost:3000/api/pedido_resolucion/68a6030df79bcb7325157d3e
