### Get All
GET http://localhost:3000/api/usuario

### Get One
GET http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d

### Post
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
    "codigo": "20",
    "nombre": "Pedro",
    "mail": "pedro@gmail.com",
    "password": "1234",
    "tipo": "operador",
    "zona": "68a1df3092d085a2634a06db"
}

###Post 2
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
    "codigo": "30",
    "nombre": "Maximo",
    "mail": "maximo@gmail.com",
    "password": "7890",
    "tipo": "cazador",
    "zona": "68a1df3092d085a2634a06db"
}

###Post 3
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
    "codigo": "40",
    "nombre": "Juan",
    "mail": "juan@gmail.com",
    "password": "abdc",
    "tipo": "cazador",
    "zona": "68a1df3092d085a2634a06db"
}

### Put
PUT http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d
Content-Type: application/json

{
  "codigo": "89999999",
  "nombre": "vegetta"
}


### Patch
PATCH http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d
Content-Type: application/json

{
  "nombre": "JACKKKKKKKKKK"
}

### Delete
DELETE http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d
