### Get All
GET http://localhost:3000/api/usuario

### Get One
GET http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d

### Post
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
    //"codigo": "20",
    "nombre_usuario": "Pedro",
    "email_usuario": "pedro@gmail.com",
    "password_usuario": "1234",
    "tipo_usuario": "operador",
    "zona": "68a1df3092d085a2634a06db"
}

###Post 2
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
    //"codigo": "30",
    "nombre_usuario": "Maximo",
    "email_usuario": "maximo@gmail.com",
    "password_usuario": "7890",
    "tipo_usuario": "cazador",
    "zona": "68a1df3092d085a2634a06db"
}

###Post 3
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
    //"codigo": "40",
    "nombre_usuario": "Juan",
    "email_usuario": "juan@gmail.com",
    "password_usuario": "abdc",
    "tipo_usuario": "cazador",
    "zona": "68a1df3092d085a2634a06db"
}

### Put
PUT http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d
Content-Type: application/json

{
  //"codigo": "89999999",
  "nombre_usuario": "vegetta"
}


### Patch
PATCH http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d
Content-Type: application/json

{
  "nombre_usuario": "JACKKKKKKKKKK"
}

### Delete
DELETE http://localhost:3000/api/usuario/68a1e4066af269bb88016f1d
