### Recurso web de nuestra api

### Obtener todos
GET http://localhost:3000/api/tipo_anomalia

### Obtener 1
GET http://localhost:3000/api/tipo_anomalia/68a646261d26f864e87d8b9c

### Crear Tipo anomalia 1
POST http://localhost:3000/api/tipo_anomalia
Content-Type: application/json

### Crear Tipo anomalia 2
POST http://localhost:3000/api/tipo_anomalia
Content-Type: application/json

{
  "nombre_tipo_anomalia": "Cable Cortado", 
  "dificultad_tipo_anomalia": 4
}

### Crear Tipo anomalia 3
POST http://localhost:3000/api/tipo_anomalia
Content-Type: application/json

{
  "nombre_tipo_anomalia": "Pérdida de Agua", 
  "dificultad_tipo_anomalia": 3
}

### Modificar entero
PUT http://localhost:3000/api/tipo_anomalia/68a646261d26f864e87d8b9c
Content-Type: application/json

{
  "nombre_tipo_anomalia": "Ejército de Zombies", 
  "dificultad_tipo_anomalia": 3
}

### modificar (PATCH - recurso parcial)
PATCH http://localhost:3000/api/tipo_anomalia/68a646261d26f864e87d8b9c
Content-Type: application/json

{
  "nombre_tipo_anomalia": "Fantasma de Ricardo Fort"
}

###
PATCH http://localhost:3000/api/tipo_anomalia/68a646261d26f864e87d8b9c
Content-Type: application/json

{
  "dificultad_tipo_anomalia": 1
}

### Eliminar 1
DELETE http://localhost:3000/api/tipo_anomalia/68adbef3a29da26ee8479432