### obtener todos los denunciantes
GET http://localhost:3000/api/denunciantes


### obtener un denunciante
GET http://localhost:3000/api/denunciantes/68a5d249e44233a23cf67d8d


### crear un nuevo denunciante
POST http://localhost:3000/api/denunciantes
Content-Type: application/json

{
  "nombre_apellido_denunciante": "Juan Pepe",
  "telefono_denunciante": "3413123456",
  "email_denunciante": "juanPepe@gmail.com"
}


### modificar un denunciante
PUT http://localhost:3000/api/denunciantes/68a5d249e44233a23cf67d8d
Content-Type: application/json

{
  //"cod_den": 2,
  "nombre_apellido_denunciante": "Pepito",
  "telefono_denunciante": "3415456789",
  "email_denunciante": "pepito@gmail.com"
}


### modificar un denunciante
PATCH http://localhost:3000/api/denunciantes/689a00bc208005874aea0fe0
Content-Type: application/json

{
  "nombre_apellido_denunciante": "Harry",
  "email_denunciante": "harry@gmail.com"
}


### borrar un denunciante
DELETE http://localhost:3000/api/denunciantes/689a00bc208005874aea0fe0