###GetAll localides
GET http://localHost:3000/api/localidad

### GetOne 
GET http://localHost:3000/api/localidad/689d01428ca37388418ffc2f

### Put
POST http://localHost:3000/api/localidad
Content-Type: application/json

{
    "codigo_localidad": "1000",    
    "nombre_localidad": "Buenos Aires"
}

### Put 2

POST http://localHost:3000/api/localidad
Content-Type: application/json

{
    "codigo_localidad": "2000",    
    "nombre_localidad": "Rosario"
}

### Put 3

POST http://localHost:3000/api/localidad
Content-Type: application/json

{
    "codigo_localidad": "99501",    
    "nombre_localidad": "Anchorage"
}

### Modificacion Parcial
PATCH http://localHost:3000/api/localidad/68a5d0c4451193c766dd40a9
Content-Type: application/json

{  
    "nombre_localidad": "CIUDAD DE Buenos Aires"
}

###
PUT http://localHost:3000/api/localidad/68a5d0c4451193c766dd40a9
Content-Type: application/json

{  
    "codigo_localidad": "7777",
    "nombre_localidad": "Cordoba"
}


### Remove
DELETE http://localHost:3000/api/localidad/68a5d0c4451193c766dd40a9