###GetAll localides
GET http://localHost:3000/api/localidad
 
### GetOne 
GET http://localHost:3000/api/localidad/689d01428ca37388418ffc2f

### Put
POST http://localHost:3000/api/localidad
Content-Type: application/json

{
    "codigo": "1000",    
    "nombre": "Buenos Aires"
}



### Put 2

POST http://localHost:3000/api/localidad
Content-Type: application/json

{
    "codigo": "2000",    
    "nombre": "Rosario"
}

### Put 3

POST http://localHost:3000/api/localidad
Content-Type: application/json

{
    "codigo": "99501",    
    "nombre": "Anchorage"
}

### Modificacion Parcial
PATCH http://localHost:3000/api/localidad/689d01428ca37388418ffc2f
Content-Type: application/json

{  
    "nombre": "CIUDAD DE Buenos Aires"
}

###
PUT http://localHost:3000/api/localidad/689d01428ca37388418ffc2f
Content-Type: application/json

{  
    "codigo": "7777",
    "nombre": "Cordoba"
}


### Remove
DELETE http://localHost:3000/api/localidad/689d01428ca37388418ffc2f