### Get All
GET http://localhost:3000/api/zona

### Get One
GET http://localhost:3000/api/zona/

### Post
POST http://localhost:3000/api/zona/
Content-Type: application/json

{
  "codigo": 5,
  "nombre": "Oeste",
  "localidad": "689d01428ca37388418ffc2f"
}

###Post 2
POST http://localhost:3000/api/zona/
Content-Type: application/json

{
  "codigo": 2,
  "nombre": "Norte",
  "localidad": "689d01428ca37388418ffc2f"
}

###Post 3
POST http://localhost:3000/api/zona/
Content-Type: application/json

{
  "codigo": 20,
  "nombre": "Este",
  "localidad": "689d01428ca37388418ffc2f"
}

### Put
PUT http://localhost:3000/api/zona/689d490f21ed66d1570cdc74
Content-Type: application/json

{
  "codigo": "89999999",
  "nombre": "mordor"
}



### Patch
PATCH http://localhost:3000/api/zona/689d490f21ed66d1570cdc74
Content-Type: application/json

{
  "nombre": "ODESA"
}

### Delete
DELETE http://localhost:3000/api/zona/689d49d621ed66d1570cdc76
