### Get All
GET http://localhost:3000/api/zona

### Get One
GET http://localhost:3000/api/zona/

### Post
POST http://localhost:3000/api/zona/
Content-Type: application/json

{
  "nombre_zona": "Oeste",
  "localidad": "68b1837c3a53299465765cb6"
}

###Post 2
POST http://localhost:3000/api/zona/
Content-Type: application/json

{
  "nombre_zona": "Norte",
  "localidad": "68b1837c3a53299465765cb6"
}

###Post 3
POST http://localhost:3000/api/zona/
Content-Type: application/json

{
  "nombre_zona": "Este",
  "localidad": "68a5d0c0451193c766dd40a8"
}

### Put
PUT http://localhost:3000/api/zona/68b35c3e53da70f4da1ec96e
Content-Type: application/json

{
  "nombre_zona": "Ala"
}



### Patch
PATCH http://localhost:3000/api/zona/68a5d1e7e44233a23cf67d8a
Content-Type: application/json

{
  "nombre_zona": "ODESA"
}

### Delete
DELETE http://localhost:3000/api/zona/68a5d1e7e44233a23cf67d8a
